/**
 * Created by wdd on 2017/2/8.
 */
export const useMock = true;
export const mockAppList = [
    {
        "Id": 1,
        "name": "王鹏",
        "departName": "开发实施五组",
        "userName": "18261521439",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 13,
        "time": "1484126318"
    },
    {
        "Id": 2,
        "name": "缪镇",
        "departName": "销售部",
        "userName": "15190942552",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 2,
        "time": "1484126333"
    },
    {
        "Id": 3,
        "name": "单学春",
        "departName": "开发实施四组",
        "userName": "13382638050",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484127096"
    },
    {
        "Id": 4,
        "name": "杨双红",
        "departName": "开发实施五组",
        "userName": "18606158699",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 10,
        "time": "1484127680"
    },
    {
        "Id": 5,
        "name": "杜雁华",
        "departName": "开发实施三组",
        "userName": "18550148386",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 2,
        "time": "1484127802"
    },
    {
        "Id": 6,
        "name": "邱坚",
        "departName": "技术服务部",
        "userName": "15906296203",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 10,
        "time": "1484642720"
    },
    {
        "Id": 7,
        "name": "杨燕龙",
        "departName": "软件技术研究院",
        "userName": "18651385283",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 6,
        "time": "1484141436"
    },
    {
        "Id": 8,
        "name": "陈光",
        "departName": "技术服务部",
        "userName": "18115610276",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 3,
        "time": "1484699186"
    },
    {
        "Id": 10,
        "name": "张伟",
        "departName": "销售部",
        "userName": "15851206670",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484145348"
    },
    {
        "Id": 11,
        "name": "蔡亚军",
        "departName": "软件技术研究院",
        "userName": "18751328538",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 3,
        "time": "1484651826"
    },
    {
        "Id": 12,
        "name": "顾海东",
        "departName": "技术服务部",
        "userName": "18762859675",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484178792"
    },
    {
        "Id": 13,
        "name": "徐保龙",
        "departName": "技术服务部",
        "userName": "18705170825",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 2,
        "time": "1484653875"
    },
    {
        "Id": 14,
        "name": "赵亢",
        "departName": "技术服务部",
        "userName": "15052739317",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 2,
        "time": "1484646129"
    },
    {
        "Id": 15,
        "name": "施东海",
        "departName": "软件技术研究院",
        "userName": "15996648639",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180411"
    },
    {
        "Id": 16,
        "name": "严勇",
        "departName": "开发实施三组",
        "userName": "13773656328",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180488"
    },
    {
        "Id": 17,
        "name": "张馨",
        "departName": "开发实施五组",
        "userName": "13770730931",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180508"
    },
    {
        "Id": 18,
        "name": "邵敏",
        "departName": "开发实施四组",
        "userName": "13921486417",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180659"
    },
    {
        "Id": 19,
        "name": "王婧",
        "departName": "开发实施一组",
        "userName": "13813143526",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180766"
    },
    {
        "Id": 20,
        "name": "朱明静",
        "departName": "开发实施六组",
        "userName": "18852962466",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484180834"
    },
    {
        "Id": 21,
        "name": "薛海涛",
        "departName": "技术服务部",
        "userName": "15190941822",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 5,
        "time": "1484911247"
    },
    {
        "Id": 22,
        "name": "邢杜锋",
        "departName": "开发实施四组",
        "userName": "13773836186",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 3,
        "time": "1484729453"
    },
    {
        "Id": 23,
        "name": "王香萍",
        "departName": "财务(办公)部",
        "userName": "18762856510",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484181073"
    },
    {
        "Id": 24,
        "name": "崔菲霏",
        "departName": "测试工作组",
        "userName": "18917554268",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484181125"
    },
    {
        "Id": 25,
        "name": "朱春琴",
        "departName": "开发实施五组",
        "userName": "13915381528",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484181177"
    },
    {
        "Id": 26,
        "name": "吴友飞",
        "departName": "管理部",
        "userName": "15851209904",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484181190"
    },
    {
        "Id": 27,
        "name": "高阳琴",
        "departName": "技术服务部",
        "userName": "13921677460",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484181966"
    },
    {
        "Id": 28,
        "name": "施园秀",
        "departName": "技术服务部",
        "userName": "18015940750",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 2,
        "time": "1486519698"
    },
    {
        "Id": 29,
        "name": "李琦",
        "departName": "测试工作组",
        "userName": "15051263638",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484182023"
    },
    {
        "Id": 30,
        "name": "印吴燕",
        "departName": "开发实施六组",
        "userName": "15062763769",
        "terminalType": "",
        "phoneType": "",
        "sysVersion": "",
        "appVersion": "",
        "deviceId": "",
        "times": 1,
        "time": "1484182088"
    },
    {
        "Id": 32,
        "name": "陈俊霖",
        "departName": "软件技术研究院",
        "userName": "18662902121",
        "terminalType": "pc",
        "phoneType": "pc",
        "sysVersion": "win10",
        "appVersion": "76",
        "deviceId": "00:50:56:C0:00:01",
        "times": 76,
        "time": "1486513911"
    }
];